### ISSUE TITLE
Cyrillic taxonomy navigation error

### ISSUE THREAD

**Issue by vglu** [vantagedesign/ace-documentation#12]
Hi

I have got error with Cyrillic taxonomy during navigarion.
Examle: on other theme works good http://localhost:1313/targetsystems/%D0%B1%D0%B0%D0%BD%D0%BA/

taxonomy setup looks like

[taxonomies]
    tag = "tags"
    category = "categories"
    targetsystem = "targetsystems"

In Ace-documentation theme this link looks like:

http://localhost:1313/targetsystems/%C3%90%C2%B1%C3%90%C2%B0%C3%90%C2%BD%C3%90%C2%BA/

Language - ru

Thanks

Regards,
Vitaliy

**Comment by julianflapper** [comment]
@vglu hi, thank you for this bug report.

Is this specific to Cyrillic or does it just not work in general? 
I can run a test but without more information regarding your setup and what you wish to achieve, I am not sure if I can solve this properly.

**Comment by vglu** [comment]
For en letters “targetsystems” works fine
Try to setup tag to value банк, for example and then navigate to it ...

**Comment by julianflapper** [comment]
@vglu Hm alright I'll look into it. 
Which theme does work with your setup? So that I can compare Ace with a working example

**Comment by vglu** [comment]
On hugo-theme-techdoc - works fine
do you need more info (scree shot, anything else)?

**Comment by julianflapper** [comment]
@vglu no thanks, I think I'm fine. I will look into fixing this for the new release. I'll keep you updated
