### ISSUE TITLE
Feature request: A option to set menu always expanded.

### ISSUE THREAD

**Issue by hyacinthus** [vantagedesign/ace-documentation#13]
Screen is large, menu is short sometimes.

It would be much clearer if the menu was always expanded.

**Comment by julianflapper** [comment]
@hyacinthus might be a good idea, will look into it

**Comment by OlegPahhomov** [comment]
That would be great!

**Comment by ppinkhasov** [comment]
@julianflapper Hi Julian, did you ever end up taking a look at this? Thnx!

**Comment by dagerzuga** [comment]
Are you talking about having the siblings always visible?

![Screen Shot 2022-11-10 at 18 18 54](https://user-images.githubusercontent.com/19642693/201233106-a324d30a-3239-414c-a385-d2f09513c3f6.png)

**Comment by hyacinthus** [comment]
Yes, but now I'm using https://github.com/google/docsy ...
