### ISSUE TITLE
How can I resize image to fit in different devices?

### ISSUE THREAD

**Issue by poonamshah** [vantagedesign/ace-documentation#14]
How can I resize image to fit in different devices?

**Comment by julianflapper** [comment]
Hi,

You can use "img-fluid" as a class on images to make them spread the width of the container with automatic height. Smaller screens would simply shrink the image down that way. This is a Bootstrap class ([https://getbootstrap.com/docs/4.5/content/images/]).
There currently is no shortcode in Ace to support this natively, so you just have to add the HTML element with that class.
