### ISSUE TITLE
Question: Multiple projects

### ISSUE THREAD

**Issue by figaro73** [vantagedesign/ace-documentation#17]
I really like this theme. I’ve looked through more on the net, but this is the one I like best. However, I would like to see the documentation of several projects in one place. At the moment, I have not found a solution with this theme. Can it be possible at all? Sorry for my english :)

**Comment by julianflapper** [comment]
Hi,

Thanks for your interest in Ace.

You can add the documentation of several projects in one place, by simply making the proper folder structure:

/content
-- /project1
-- -- _index.md
-- -- pages
-- /project2
-- -- _index.md
-- -- pages
-- /project3
-- -- _index.md
-- -- pages

Though it will never be quite like a fully separated documentation.
