### ISSUE TITLE
is it possible to change the colours? 

### ISSUE THREAD

**Issue by laurapoggio-sptools** [vantagedesign/ace-documentation#18]
I would be interested in changing the colours, especially of the menubar.
Is it possible? 

Thanks

**Comment by julianflapper** [comment]
Hi!

Yes it is for sure!

If you have the extended version of Hugo, you can modify the theme's source SCSS files to change the variable of the primary color to a custom color.

**Comment by laurapoggio-sptools** [comment]
Thank you very much!
it worked.
