### ISSUE TITLE
No menu bar while deploying using github pages

### ISSUE THREAD

**Issue by PRUBHTEJ** [vantagedesign/ace-documentation#20]
While I'm deploying the same website on github pages I'm unable to see the menu bar on the left hand side whereas, if I'm running it locally, then everything seems fine.
I'm attaching the screenshots below. Kindly suggest.
![Screenshot from 2020-09-15 01-15-30](https://user-images.githubusercontent.com/47414674/93131052-18b09b80-f6f1-11ea-8e99-129c5ea88d95.png)
![Screenshot from 2020-09-15 01-15-59](https://user-images.githubusercontent.com/47414674/93131058-1bab8c00-f6f1-11ea-81b0-e48a1f6671b1.png)

**Comment by julianflapper** [comment]
Hi,

I've checked your site and it seems like the site is unable to load core dependencies, such as jquery, popper, bootstrap, etc.

Please check if your JavaScript files are being properly loaded on remote domains. Perhaps the base URL is misconfigured.

**Comment by PRUBHTEJ** [comment]
Greetings,
Thanks for your help!
It worked, I changed the base URL as well as did hugo -D and it surprisingly ran!!

**Comment by PRUBHTEJ** [comment]
Greetings,
Actually I am trying to arrange the menu in a customized manner, but I'm unable to do so.
Could you please guide me in some way?

**Comment by julianflapper** [comment]
Could you be more specific?

**Comment by PRUBHTEJ** [comment]
My website is currently live on synbiohub.github.io and I'm trying to customize the menu order i.e.  not using the regular alphabetical order.

**Comment by julianflapper** [comment]
You can use the weight option in a page's configuration to list it higher or lower.

**Comment by PRUBHTEJ** [comment]
Thank for the reply!!
I'll close this issue now.

**Comment by PRUBHTEJ** [comment]
I've to edit the weights in the config.toml file or in the specific _index.md file?

**Comment by julianflapper** [comment]
In each .md file for a page, same place where you set the title of a page. The example site might have it

**Comment by PRUBHTEJ** [comment]
I tried that by adding "weight:value" term but nothing worked, could you please share the link to the example site?

Also what should be that value that should be assigned to the page of highest priority?

**Comment by julianflapper** [comment]
https://raw.githubusercontent.com/vantagedesign/ace-documentation/master/exampleSite/content/getting-started/installation.md

There is an example for the exampleSite pages.
A higher weight places it lower in the order, I think.

**Comment by PRUBHTEJ** [comment]
Greetings,
Thanks!!
This issue has been resolved.
