### ISSUE TITLE
Unable to scroll down the Sections Bar on the RHS 

### ISSUE THREAD

**Issue by PRUBHTEJ** [vantagedesign/ace-documentation#26]
There is a sections bar on the RHS of [this](https://synbiohub.github.io/plugins/) page, but I'm unable to scroll it down. 
It displays only 3 sections whereas I've got more than 8 sections on this page. 
How can I solve this issue?

**Comment by PRUBHTEJ** [comment]
Hope to hear from you soon!!

**Comment by julianflapper** [comment]
Hi, will investigate this issue in the coming week. Apologies for slow response, very busy with other stuff!

**Comment by PRUBHTEJ** [comment]
No issues, @julianflapper!

**Comment by PRUBHTEJ** [comment]
Is there any update for this issue, @julianflapper ?

**Comment by julianflapper** [comment]
@PRUBHTEJ fixed in latest commit, pull changes from this branch or simply add:
```overflow:auto;``` to ```.docs-sidenav, .docs-toc``` in ```assets/css/ace.scss```
