### ISSUE TITLE
How to enable lunr.js search?

### ISSUE THREAD

**Issue by nategoethel** [vantagedesign/ace-documentation#28]
Can somebody give a quick breakdown of what I need to do to enable lunr.js?

**Comment by julianflapper** [comment]
Hi, will look into this in the coming week. Apologies for slow response, very busy with other stuff!

**Comment by julianflapper** [comment]
@nategoethel this should be enabled by default, out of the box. Make sure the following variable is set to false in your config.toml;
```disableSearch = false # default is false```
