### ISSUE TITLE
Clicking on a link opens up the page in a new tab.

### ISSUE THREAD

**Issue by PRUBHTEJ** [vantagedesign/ace-documentation#32]
Is there an option using which, there is a possibility that when the user clicks a particular link, it opens that particular link in a new tab?

**Comment by PRUBHTEJ** [comment]
Hope to hear from you soon.

**Comment by julianflapper** [comment]
@PRUBHTEJ use an anchor tag with `target="_blank"`:
```
< a href="google.com" target="_blank"></a>
```

**Comment by PRUBHTEJ** [comment]
Where should I insert this, so that this works on all the pages?

**Comment by julianflapper** [comment]
This is for a single link on a page.
 It does not work on menu's and such. If you want it on menu's, modify the links in the theme's partials for the menu and navbar to also include target blank.

**Comment by PRUBHTEJ** [comment]
Yes, so I want it for all the links, so then what should be the procedure?

**Comment by julianflapper** [comment]
https://github.com/vantagedesign/ace-documentation/blob/master/layouts/partials/menu.html

So in partials like this, add target blank to the <a> elements.

**Comment by PRUBHTEJ** [comment]
Great!
Thank you so much @julianflapper!
